---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: onsdigital/dp-concourse-tools-node-go

inputs:
  - name: dp-frontend-filter-dataset-controller
    path: go/src/github.com/ONSdigital/dp-frontend-filter-dataset-controller

outputs:
  - name: build

run:
  path: go/src/github.com/ONSdigital/dp-frontend-filter-dataset-controller/ci/scripts/build.sh
