---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tags: 1.12.12

inputs:
  - name: dp-frontend-filter-dataset-controller
    path: dp-frontend-filter-dataset-controller

outputs:
  - name: build

run:
  path: dp-frontend-filter-dataset-controller/ci/scripts/build.sh
