---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.8.3

inputs:
  - name: dp-frontend-filter-dataset-controller
    path: go/src/github.com/ONSdigital/dp-frontend-filter-dataset-controller

outputs:
  - name: bin

run:
  path: go/src/github.com/ONSdigital/dp-frontend-filter-dataset-controller/ci/scripts/build.sh
